### ISSUE TITLE
autoSetup.pl zookeeper installation is not working as of version 3.5.5

### ISSUE THREAD

**Issue by kushmerick** [vmware/weathervane#140]
this line from autoSetup.pl https://github.com/vmware/weathervane/blob/f3f3c4df4557f97c7e2705fd6594eaec47b33843/autoSetup.pl#L344
assumes that the zookeeper tarball name starts with 'zookeeper'.  but as of version 3.5.5 it actually it starts with 'apache-zookeeper'.  as a result, autoSetup.pl fails to installl zookeeper.

**Comment by fraziermatthew** [comment]
I'm having the same issue when installing zookeeper

**Comment by hrosenbe** [comment]
Sorry about the slow response on this.  With our work on Weathervane 2.0 we do not currently have a testbed for testing fixes for the 1.x release.  I will try to get to this soon, but probably will not be able to test a fix until next week.

**Comment by bhoflich** [comment]
Closing version 1.x issue, which is no longer being maintained.
