### ISSUE TITLE
Repo significantly broken, due to use of unsupported and now non existent CentOS7

### ISSUE THREAD

**Issue by russfellows** [vmware/weathervane#258]
### Describe the bug

There are a MYRIAD of problems and errors, almost all of which stem from the use of the now completely dead CentOS7 as the base container image for this repo.  The knowledge of CentOS's demise has been known for several years, so the fact that nothing has been done is somewhat surprising.  

### Reproduction steps

1. Follow the quickstart guide.
2. You will immediately receive MANY errors when attempting to build the first container "centos". 
3. If you can figure out how to remedy these issues, there are then MANY errors building subsequent containers
...

### Expected behavior

The expected behavior is that the quickstart guide would actually work.  

### Additional context

Please update this entire repo to utilize a modern, supported base OS image.  CentOS stream is not really a good option, but perhaps could suffice.  There are MANY alternatives "Rocky Linux", "AlmaLinux", RHEL 9, Oracle, Ubuntu, etc.

**Comment by russfellows** [comment]
Please update this repo if you expect anyone to use it in 2024 or beyond.

**Comment by russfellows** [comment]
Mistakenly closed while trying to save.

**Comment by bhoflich** [comment]
Version 2.2.0 moves off of Centos7.

**Comment by bhoflich** [comment]
Version 2.2.0 moves off of Centos7.
