### ISSUE TITLE
Weathervane also has MAJOR issues by using PostgreSQL 9.3, which has been non existent for several years

### ISSUE THREAD

**Issue by russfellows** [vmware/weathervane#259]
### Describe the bug

Once again, by hardcoding this repo, to build and depend upon ancient software that hasn't been supported for many years, and is no longer available, there are significant issues.  If you instead had created a standalone container that actually had postgreSQL 9.3 installed within it, this could work.  But trying to build it, in this day and age is nearly impossible.  It is like asking someone to build the orginal DOS OS without having access to compilers, linkers loaders or hardware that existed from the early 1980s.  

### Reproduction steps

1. git pull weathervane
2. type "./buildDockerImages.pl" and watch the endless errors due the non existence of 10 year old software.
3.
...

### Expected behavior

It is expected that step 2 of the getting started guide would not fail quite so miserably.  

### Additional context

If this project is expected to live, it needs SERIOUS work, starting by updating to using either software packages that can be dowloaded and installed, or perhaps NOT requiring their installation at all, but rather building complete docker images that include all software.

**Comment by bhoflich** [comment]
Version 2.2.0 updates software versions of many packages.
