### ISSUE TITLE
Issues building images due to hardcoded "FROM" in Dockerfile

### ISSUE THREAD

**Issue by embano1** [vmware/weathervane#30]
**Command:** 
`./buildDockerImages.pl --private --host 172.16.108.130 --port 5000`

**Result (from the .log):**
`Sending build context to Docker daemon 205.8 kB
Step 1/8 : FROM 10.159.13.130:5000/centos7ssh:1.0b5
Get https://10.159.13.130:5000/v1/_ping: dial tcp 10.159.13.130:5000: getsockopt: connection refused
COMMAND> docker push 172.16.108.130:5000/weathervane-tomcat:1.0.12
The push refers to a repository [172.16.108.130:5000/weathervane-tomcat]
An image does not exist locally with the tag: 172.16.108.130:5000/weathervane-tomcat`

**Quick fix:** (e.g. nginx Dockerfile)
`FROM 172.16.108.130:5000/centos7ssh:1.0.12`

Is it just me getting this error (although I tried to 100% follow the user guide) or does the .pl script not change the values in the corresponding Dockerfiles (bug)?

**Comment by hrosenbe** [comment]
This was indeed a bug.  As you saw, the buildDockerImages script needed to rewrite the Dockerfiles to pull the base image from the repository.  

This is fixed in c3952142d17878ad479d2703b232cc2d33ad8c77 and this fixed is contained in release 1.0.14.
