### ISSUE TITLE
Error message when Java is not installed

### ISSUE THREAD

**Issue by RGrider** [vmware/weathervane#52]
When installing Weathervane on CentOS 7.4 release 1708, running "./gradlew clean release" without having first installed jdk ("yum install –y java-1.8.0-openjdk*") will produce an error:

"Could not find tools.jar"

![image](https://user-images.githubusercontent.com/22941180/31103390-46b4d5ca-a79c-11e7-9fb1-1f5071400064.png)

This is different than the error described in the User's Guide, "you may get an error that no java command could be found in your path." It may be that CentOS 7.4 minimal install includes the JRE but not the JDK. Consider adding the error, such as seen in the screenshot, to the User's Guide in section 3.5.

**Comment by hrosenbe** [comment]
Release 1.0.17 will download java and build the executables in the autoSetup script.  See #58.  Therefore this part of the user's guide will be removed.

**Comment by hrosenbe** [comment]
Fixed in Release 1.0.17
